apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tlaokas-ingress
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.ingress.certificateArn }}"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: tlaokas-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tlaokas-frontend
                port:
                  number: 80
